.. |krita_logo| image:: _static/images/sphinxdocs/krita-logo.png
.. |krita16| image:: _static/images/sphinxdocs/krita_favicon16.png
.. |python| image:: _static/images/sphinxdocs/python.png

.. |nbsp| unicode:: 0xA0
   :trim:

.. .. External Hyperlinks

.. _2014 Kickstarter: https://www.kickstarter.com/projects/krita/krita-open-source-digital-painting-accelerate-deve
.. _2015 Kickstarter: https://www.kickstarter.com/projects/krita/krita-free-paint-app-lets-make-it-faster-than-phot
.. _2016 Kickstarter: https://www.kickstarter.com/projects/krita/krita-2016-lets-make-text-and-vector-art-awesome
.. _Python: https://www.python.org/

